version: "3.4"
services:
  vite_docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite_docker
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./
        target: /app
